const getContextObject = require('../utils/context-object')
const { parseReadUrl } = require('../utils/parse-url')
const handleError = require('../utils/handle-error')
const { getError } = require('../../../errors')

const _convertCustomOperationReturnValue = (returns, result) => {
  if (returns.items) {
    return result
  }

  return Array.isArray(result) ? result[0] : result
}

const read = service => {
  return (req, res) => {
    let parsedUrl

    try {
      parsedUrl = parseReadUrl(service, req)
    } catch (err) {
      return handleError(err, service, res)
    }

    const context = getContextObject(service, parsedUrl, req, res)

    if (parsedUrl.customOperation) {
      const operation = parsedUrl.segments[parsedUrl.segments.length - 1]

      return service
        .processEvent(context)
        .then(result => {
          // TODO: validation for correct return type
          if (!operation.returns) {
            return res.status(204).send()
          }

          res.status(200)
          res.send(_convertCustomOperationReturnValue(operation.returns, result))
        })
        .catch(err => {
          // Hide errors in generic message but log detailed error
          handleError(err, service, res)
        })
    }

    return service
      .processEvent(context)
      .then(result => {
        context.emit('succeeded')
        context.emit('done')

        if (parsedUrl.isCollection) {
          res.status(200)
          res.send(result)

          return
        }

        if (result.length !== 1) {
          throw getError(404, 'The server has not found a resource matching the Data Services Request URI.')
        }

        res.status(200)
        res.send(result[0])
      })
      .catch(err => {
        context.emit('failed', err)
        context.emit('done')

        // Hide errors in generic message but log detailed error
        handleError(err, service, res)
      })
  }
}

module.exports = read
